# Created by: Dmitry Salychev <dsl@mcusim.org>
# $FreeBSD$

PORTNAME=	u-boot-honeycomb
PORTVERSION=	2021.04
CATEGORIES=	sysutils
UBOOT_COMMIT=	b46dd116ce03e235f2a7d4843c6278e1da44b5e1
MASTER_SITES=	https://source.codeaurora.org/external/qoriq/qoriq-components/u-boot/snapshot/
DISTNAME=	${UBOOT_COMMIT}

MAINTAINER=	dsl@mcusim.org
COMMENT=	Cross-build das u-boot for model HoneyComb LX2

LICENSE=	GPLv2

.include <bsd.port.mk>
