# Created by: Dmitry Salychev <dsl@mcusim.org>
# $FreeBSD$

PORTNAME=	u-boot-honeycomb
PORTVERSION=	20.12
CATEGORIES=	sysutils
UBOOT_COMMIT=	f46a944f715f284aff1d42c009680ffe0be4058f
MASTER_SITES=	https://source.codeaurora.org/external/qoriq/qoriq-components/u-boot/snapshot/
DISTNAME=	${UBOOT_COMMIT}

MAINTAINER=	dsl@mcusim.org
COMMENT=	Cross-build das u-boot for model HoneyComb LX2

LICENSE=	GPLv2

.include <bsd.port.mk>
